server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://acv-compare-backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /calc {
        proxy_pass http://ventum-openlca-bridge:3000/ventum-acv;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /status {
        proxy_pass http://uptime-kuma:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        set $url_prefix subpath;
        rewrite ^/subpath/?(.*)$ /$1 break;

        proxy_redirect ^ /$url_prefix;
        proxy_redirect /dashboard /$url_prefix/dashboard;
        proxy_redirect /status/ /$url_prefix/status/;
        proxy_redirect /upload/ /$url_prefix/upload/;
        proxy_redirect /upload/logo1.png /$url_prefix/upload/logo1.png;

        proxy_set_header Accept-Encoding "";
        sub_filter_last_modified on;
        sub_filter_once off;
        sub_filter_types *;
        sub_filter '/assets/' '/$url_prefix/assets/';
        sub_filter '"assets/' '"$url_prefix/assets/';
        sub_filter '/socket.io' '/$url_prefix/socket.io';
        #sub_filter '/icon.svg' '/$url_prefix/icon.svg';
        sub_filter '/favicon.ico' '/$url_prefix/favicon.ico';
        sub_filter '/apple-touch-icon.png' '/$url_prefix/apple-touch-icon.png';
        sub_filter '/manifest.json' '/$url_prefix/manifest.json';
        sub_filter '/add' '/$url_prefix/add';
        sub_filter '/settings/' '/$url_prefix/settings/';
        sub_filter '"/settings' '"/$url_prefix/settings';
        sub_filter '/dashboard' '/$url_prefix/dashboard';
        sub_filter '/maintenance' '/$url_prefix/maintenance';
        sub_filter '/add-status-page' '/$url_prefix/add-status-page';
        sub_filter '/manage-status-page' '/$url_prefix/manage-status-page';
        sub_filter '"/status/' '"/$url_prefix/status/';
        sub_filter '/upload/' '/$url_prefix/upload/';
        sub_filter '/api/' '/$url_prefix/api/';
        sub_filter '/upload/logo1.png' '/subpath/upload/logo1.png';
        sub_filter '/setup' '/$url_prefix/setup';
    }
}